# Generated by Django 5.0.1 on 2024-02-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_alter_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
