# Generated by Django 5.0.1 on 2024-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_comment_author_alter_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
