# Generated by Django 5.0.1 on 2024-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0008_task_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
